[package]
name = "starknet_mempool_integration_tests"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
axum.workspace = true
hyper.workspace = true
itertools.workspace = true
reqwest.workspace = true
starknet_api.workspace = true
starknet_gateway = { path = "../gateway", version = "0.0", features = ["testing"] }
starknet_mempool = { path = "../mempool", version = "0.0" }
starknet_mempool_types = { path = "../mempool_types", version = "0.0" }
starknet_task_executor = { path = "../task_executor", version = "0.0" }
tokio.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
rstest.workspace = true
starknet_mempool_infra = { path = "../mempool_infra", version = "0.0" }
