[package]
name = "gateway"
version.workspace = true
edition.workspace = true

[dependencies]
hyper.workspace = true
tokio.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
starknet_api.workspace = true
assert_matches.workspace = true
starknet-crypto.workspace = true
hex.workspace = true
lazy_static.workspace = true
papyrus_common.workspace = true



[lib]
name = "gateway_lib"
