[package]
name = "starknet_gateway"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
assert_matches.workspace = true
axum.workspace = true
clap.workspace = true
hyper.workspace = true
serde.workspace = true
serde_json.workspace = true
starknet_api.workspace = true
thiserror.workspace = true
papyrus_config.workspace = true
validator.workspace = true

[dev-dependencies]
rstest.workspace = true
tokio.workspace = true

