[package]
name = "starknet_gateway"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
axum.workspace = true
blockifier = { workspace = true, features = ["testing"] }
clap.workspace = true
cairo-lang-casm = { workspace = true, features = ["parity-scale-codec"] }
hyper.workspace = true
papyrus_config.workspace = true
serde.workspace = true
serde_json.workspace = true
starknet_api.workspace = true
thiserror.workspace = true
tower.workspace = true
validator.workspace = true

[dev-dependencies]
assert_matches.workspace = true
pretty_assertions.workspace = true
rstest.workspace = true
tokio.workspace = true
