[package]
name = "starknet_gateway"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
starknet_api.workspace = true
assert_matches.workspace = true
rstest.workspace = true

[lints]
workspace = true
