[package]
edition.workspace = true
license.workspace = true
name = "starknet_gateway"
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[features]
testing = []

[dependencies]
axum.workspace = true
blockifier.workspace = true
cairo-lang-starknet-classes.workspace = true
cairo-vm.workspace = true
hyper.workspace = true
indexmap.workspace = true
papyrus_common.workspace = true
papyrus_config.workspace = true
papyrus_rpc.workspace = true
papyrus_storage.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
starknet_api.workspace = true
starknet_client.workspace = true
starknet_mempool_types = { path = "../mempool_types", version = "0.0" }
starknet_sierra_compile ={ path = "../starknet_sierra_compile", version = "0.0" }
strum.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
validator.workspace = true

[dev-dependencies]
assert_matches.workspace = true
pretty_assertions.workspace = true
rstest.workspace = true
starknet_mempool = { path = "../mempool", version = "0.0" }
