[package]
name = "gateway"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror.workspace = true
starknet_api.workspace = true
assert_matches.workspace = true
rstest.workspace = true

[lib]
name = "gateway_lib"
