[package]
name = "starknet_gateway"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
testing = []

[dependencies]
axum.workspace = true
blockifier.workspace = true
cairo-lang-starknet-classes.workspace = true
hyper.workspace = true
papyrus_config.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
starknet_api.workspace = true
starknet_mempool_types = { path = "../mempool_types", version = "0.0" }
thiserror.workspace = true
tokio.workspace = true
validator.workspace = true

[dev-dependencies]
assert_matches.workspace = true
pretty_assertions.workspace = true
rstest.workspace = true
starknet_mempool = { path = "../mempool", version = "0.0" }
