[package]
name = "test_utils"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[features]

[dependencies]
assert_matches.workspace = true
blockifier.workspace = true
starknet_api.workspace = true
serde.workspace = true
serde_json.workspace = true