[workspace]
# Using version 2 to avoid unifying features. For more info, read:
#   https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2
resolver = "2"  # Specify the resolver version that matches edition 2021

members = ["crates/gateway"]

[workspace.dependencies]
starknet_api = "0.8.0"
