[workspace]
resolver = "2"
members = ["crates/gateway", "crates/mempool", "crates/mempool_node"]

[workspace.package]
version = "0.0.0"
edition = "2021"
repository = "https://github.com/starkware-libs/mempool/"
license = "Apache-2.0"

[workspace.lints.rust]
warnings = "deny"
future-incompatible = "deny"
nonstandard-style = "deny"
rust-2018-idioms = "deny"
unused = "deny"

[workspace.lints.clippy]
as_conversions = "deny"

[workspace.dependencies]
assert_matches = "1.5.0"
async-trait = "0.1.79"
axum = "0.6.12"
# TODO(YaelD, 1/5/2024): Use a fixed version once the StarkNet API is stable.
blockifier = { git = "https://github.com/starkware-libs/blockifier.git", branch = "mohammad/try1", features = ["testing"] }
clap = "4.3.10"
derive_more = "0.99"
const_format = "0.2.30"
hyper = "1.2.0"
papyrus_config = "0.3.0"
pretty_assertions = "1.4.0"
rstest = "0.17.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0"
# TODO(Arni, 1/5/2024): Use a fixed version once the StarkNet API is stable.
starknet_api = { git = "https://github.com/starkware-libs/starknet-api.git", rev = "1b46b42" }
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
tower = "0.4.13"
validator = "0.12"
