[workspace]
members = [
    "crates/gateway",
    "crates/mempool",
    "crates/mempool_types",
    "crates/mempool_node",
    "crates/mempool_infra",
    "crates/starknet_sierra_compile",
    "crates/task_executor",
]
resolver = "2"

[workspace.package]
version = "0.0.0"
edition = "2021"
repository = "https://github.com/starkware-libs/mempool/"
license = "Apache-2.0"

[workspace.lints.rust]
warnings = "deny"
future-incompatible = "deny"
nonstandard-style = "deny"
rust-2018-idioms = "deny"
unused = "deny"

[workspace.lints.clippy]
as_conversions = "deny"

[workspace.dependencies]
anyhow = "1.0"
assert_matches = "1.5.0"
async-trait = "0.1.79"
axum = "0.6.12"
# TODO(YaelD, 1/5/2024): Use a fixed version once the StarkNet API is stable.
blockifier = { git = "https://github.com/starkware-libs/blockifier.git", rev = "fc62b8b8", features = ["testing"] }
cairo-lang-sierra = "2.6.0"
cairo-lang-starknet-classes = "2.6.0"
cairo-lang-utils = "2.6.0"
clap = "4.3.10"
const_format = "0.2.30"
derive_more = "0.99"
hyper = { version = "0.14", features = ["client", "http1"] }
futures = "0.3.30"
papyrus_config = "0.3.0"
pretty_assertions = "1.4.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
rstest = "0.17.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0"
# TODO(Arni, 1/5/2024): Use a fixed version once the StarkNet API is stable.
starknet_api = { git = "https://github.com/starkware-libs/starknet-api.git", rev = "0f49f20a" }
thiserror = "1.0"
tokio = { version = "1.37.0", features = ["full"] }
tokio-test = "0.4.4"
tower = "0.4.13"
url = "2.5.0"
validator = "0.12"
