[package]
name = "mempool_node"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
clap.workspace = true
const_format.workspace = true
starknet_gateway = { path = "../gateway", version = "0.0" }
serde.workspace = true
papyrus_config.workspace = true
tokio.workspace = true
validator.workspace = true

[dev-dependencies]
assert-json-diff.workspace = true
assert_matches.workspace = true
colored.workspace = true
insta = { workspace = true, features = ["json"] }
pretty_assertions.workspace = true
serde_json.workspace = true
test_utils = {path = "../test_utils"}
