[package]
name = "starknet_mempool"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
derive_more.workspace = true
mempool_infra = { path = "../mempool_infra", version = "0.0" }
starknet_api.workspace = true
starknet_mempool_types = { path = "../mempool_types", version = "0.0" }
thiserror.workspace = true
tokio.workspace = true
async-trait.workspace = true


[dev-dependencies]
assert_matches.workspace = true
rstest.workspace = true
starknet_api = { workspace = true, features = ["testing"] }
tokio.workspace = true
