[package]
name = "starknet_task_executor"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
tokio.workspace = true

[lints]
workspace = true
