[package]
name = "starknet_mempool_infra"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[package.metadata.cargo-udeps.ignore]
normal = ["tokio"]

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
serde.workspace = true
hyper.workspace = true
papyrus_config.workspace = true
thiserror.workspace = true
tokio.workspace = true
tonic = "0.11.0"
prost = "0.12.6"
bincode = "1.3.3"

[dev-dependencies]
assert_matches.workspace = true
pretty_assertions.workspace = true

[build-dependencies]
protoc-prebuilt = "0.3.0"
tonic-build = "0.11.0"

[package.metadata.cargo-machete]
ignored = ["prost"]
