name: Nightly Latest Dependencies Check

on:
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 UTC every day

jobs:
  latest_deps:
    name: Latest Dependencies
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: dtolnay/rust-toolchain@4cda84d5c5c54efe2404f9d843567869ab1699d4 # stable
      - name: Update Dependencies
        run: cargo update --verbose
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
